Document: gimx
Title: Debian gimx Manual
Author: <insert document author here>
Abstract: This manual describes what gimx is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gimx/gimx.sgml.gz

Format: postscript
Files: /usr/share/doc/gimx/gimx.ps.gz

Format: text
Files: /usr/share/doc/gimx/gimx.text.gz

Format: HTML
Index: /usr/share/doc/gimx/html/index.html
Files: /usr/share/doc/gimx/html/*.html
